### PR TITLE
Fix padding for background-only alert web component

### PR DESCRIPTION
**Pull request by andresriveratoro**
## Description
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/32091

## Testing done

Visual (Storybook)

### Before
before

### After
after

## Acceptance criteria
- [ ] `<va-alert>` background-only variant has reduced padding

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by k80bowman — APPROVED** [review]

**Comment by GnatalieH** [comment]
@andresriveratoro can you tell me what the new padding specs are? I'm creating a mockup of a background alert with an icon to potentially incorporate into the design system. I looked in Storybook and it appears the old padding is still being displayed for background only alerts. Thanks!

**Comment by andresriveratoro** [comment]
> @andresriveratoro can you tell me what the new padding specs are? I'm creating a mockup of a background alert with an icon to potentially incorporate into the design system. I looked in Storybook and it appears the old padding is still being displayed for background only alerts. Thanks!

@GnatalieH This component's bg-only variant is now using 2rem padding on all sides. Does that answer your question?

**Comment by GnatalieH** [comment]
@andresriveratoro as far as I understand 2rem = 32 pixels. However, when I use the 32px padding it looks like it's too much:

image

Can someone confirm that 2rem = 32 pixels padding on all sides? Also, can you tell me the line height that the text is using? CC @k80bowman for visibility. Thanks!

**Comment by GnatalieH** [comment]
@andresriveratoro as far as I understand 2rem = 32 pixels. However, when I use the 32px padding it looks like it's too much. Can someone confirm that 2rem = 32 pixels padding on all sides? Also, can you tell me the line height that the text is using? CC @k80bowman for visibility. Thanks!

informational

**Comment by GnatalieH** [comment]
> > @andresriveratoro can you tell me what the new padding specs are? I'm creating a mockup of a background alert with an icon to potentially incorporate into the design system. I looked in Storybook and it appears the old padding is still being displayed for background only alerts. Thanks!
> 
> @GnatalieH This component's bg-only variant is now using 2rem padding on all sides. Does that answer your question?

2rem = 32 pixels in my understanding. If this isn't correct, please let me know! Thanks!

**Comment by k80bowman** [comment]
> > > @andresriveratoro can you tell me what the new padding specs are? I'm creating a mockup of a background alert with an icon to potentially incorporate into the design system. I looked in Storybook and it appears the old padding is still being displayed for background only alerts. Thanks!
> > 
> > 
> > @GnatalieH This component's bg-only variant is now using 2rem padding on all sides. Does that answer your question?
> 
> 2rem = 32 pixels in my understanding. If this isn't correct, please let me know! Thanks!

Since this has been merged, Storybook is now updated. When I look at this component [there](https://design.va.gov/storybook/?path=/docs/components-va-alert--default#background-only), I am seeing 2rem = 20px

**Comment by GnatalieH** [comment]
> 
> Since this has been merged, Storybook is now updated. When I look at this component [there](https://design.va.gov/storybook/?path=/docs/components-va-alert--default#background-only), I am seeing 2rem = 20px

Thank you!

**Pull request merged**
