### PR TITLE
va-text-input: require  prop to enable character count

### PR DESCRIPTION
**Pull request by it-harrison**
## Chromatic

https://2469-text-input-bug--60f9b557105290003b387cd5.chromatic.com

---

## Description
This PR alters the behavior of `va-text-input` so that it now requires the use of the `charcount` prop for the character count to display. It also fixes a bug whereby if the value of the input is an empty string the message displayed is not the default message for an untouched input.

Closes [2469](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2469)

## QA Checklist
- [x] Component maintains 1:1 parity with design mocks
- [x] Text is consistent with what's been provided in the mocks
- [x] Component behaves as expected across breakpoints
- [ ] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- [ ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [x] Tab order and focus state work as expected
- [x] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [x] New components are covered by e2e tests; updates to existing components are covered by existing test suite
- [x ] Changes have been tested in vets-website using Verdaccio (if applicable. If not applicable provide reason why)

## Screenshots
**Before**:
No `charcount` prop needed:
Screenshot 2024-02-05 at 1 49 23 PM

Demonstrating that the label text does not reset when the input value is cleared after having been giving a value:

https://github.com/department-of-veterans-affairs/component-library/assets/8867779/240d841f-3510-4f09-9087-abff3534d254

**After**
`charcount` prop now needed for char count message: 
Screenshot 2024-02-05 at 1 38 55 PM

Demonstration that the input's label displays "xx characters allowed" if the input's value returns to an empty string instead of "xx characters left": 

https://github.com/department-of-veterans-affairs/component-library/assets/8867779/adc1f1dc-95b6-4cf9-8b0f-ffbeabacfb95

## Acceptance criteria
- [ ] QA checklist has been completed
- [ ] Screenshots have been attached that cover desktop and mobile screens

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by powellkerry** [comment]
It doesn't look like the storybook examples are working. Does the stories need to be updated to include the new prop by default?

**Review by powellkerry — COMMENTED** [review]
It doesn't look like the storybook examples are working. Do the stories need to be updated to include the new prop by default?

**Comment by it-harrison** [comment]
> It doesn't look like the storybook examples are working. Does the stories need to be updated to include the new prop by default?

@powellkerry thanks - totally forgot to update storybook

**Comment by jamigibbs** [comment]
> > It doesn't look like the storybook examples are working. Does the stories need to be updated to include the new prop by default?
> 
> @powellkerry thanks - totally forgot to update storybook

Does this mean that existing usages on vets-website will need to be updated as well once this is released?

**Comment by it-harrison** [comment]
> > > It doesn't look like the storybook examples are working. Does the stories need to be updated to include the new prop by default?
> > 
> > 
> > @powellkerry thanks - totally forgot to update storybook
> 
> Does this mean that existing usages on vets-website will need to be updated as well once this is released?

@jamigibbs good question - mainly this PR is to stop the charcount from appearing where it's not wanted so I think that teams which have specified `max-length` on their instances need to be notified of the change.

**Comment by it-harrison** [comment]
@humancompanion-usds Currently the **v1** version of this component shows the [max](https://design.va.gov/storybook/iframe.html?id=components-va-text-input--default&viewMode=docs&args=#max-length) / [min](https://design.va.gov/storybook/iframe.html?id=components-va-text-input--default&viewMode=docs&args=#min-length) info whenever `max-length` is set - I have tentatively gated this behavior behind the `charcount` prop as with v3 in case there is a team using the v1 version in field in a form where this behavior is not wanted. But wanted to double check with you if I should alter from status quo.

**Comment by humancompanion-usds** [comment]
@it-harrison - That's fine.

**Review by powellkerry — APPROVED** [review]

**Review by micahchiang — APPROVED** [review]

**Pull request merged**
