### PR TITLE
Removed aria-live from breakcrumbs

### PR DESCRIPTION
**Pull request by noahgelman**
## Description
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/241

## Testing done

Tested that removing aria-polite stopped screen readers from announcing breadcrumbs when re-rendering

## Screenshots

N/A

## Acceptance criteria
- [ ] Breadcrumbs do not not announce their state when re-rendering

## Definition of done
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by 1Copenut** [comment]
@noahgelman I can't approve the PR just yet, I think I need to be added as a reviewer. While I'm doing that, would you mind bumping the version to **2.5.7** in the package.json file as part of your PR? https://github.com/department-of-veterans-affairs/component-library/blob/7faa2513c5b4223f524905d816f0f1f33b384c5d/package.json#L3

**Review by 1Copenut — CHANGES_REQUESTED** [review]
@noahgelman Would you mind bumping the version to **2.5.7** in the package.json file as part of your PR? https://github.com/department-of-veterans-affairs/component-library/blob/7faa2513c5b4223f524905d816f0f1f33b384c5d/package.json#L3

After that, this looks good to me!

**Review by bkjohnson — APPROVED** [review]
Looks good to me as well! Since Trevor requested the version bump I think that will block merging even if I approve, so I'm approving just so you don't have to wait for me to get back to this after Trevor does.

**Review by 1Copenut — APPROVED** [review]
Thanks Noah! LGTM!

**Pull request merged**
