### PR TITLE
link to npm package

### PR DESCRIPTION
**Pull request by mchelen-gov**
## Description
- link to npm package
- update design system webpage links
- remove hardcoded component list

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by cvalarida — APPROVED** [review]

**Comment by cvalarida** [comment]
:thinking: Now that I re-read that line, it should probably just say the "VA.gov design system" and leave out vets-website entirely. :man_shrugging:

**Comment by mchelen-gov** [comment]
>  Now that I re-read that line, it should probably just say the "VA.gov design system" and leave out vets-website entirely.

@cvalarida should https://github.com/department-of-veterans-affairs/design-system link be removed as well? it seems to be deprecated

**Comment by mchelen-gov** [comment]
@cvalarida i made a couple more tweaks to the readme, lmk what you think?

**Review by cvalarida — APPROVED** [review]
Looks great!

**Pull request merged**
