### PR TITLE
va-table: update va-table-inner to properly scope table header row to columns

### PR DESCRIPTION
**Pull request by 1Copenut**
## Chromatic

https://patch-tpierce-95120--65a6e2ed2314f7b8f98609d8.chromatic.com

---
## Configuring this pull request
- [x] Link to any related issues in the description so they can be cross-referenced.
- [x] Add the appropriate version patch label (`major`, `minor`, `patch`, or `ignore-for-release`).
    - See [How to choose a version number](https://github.com/department-of-veterans-affairs/component-library#how-to-choose-a-version-number) for guidance.
    - Use `ignore-for-release` if files haven't been changed in a component library package. (ie. only Storybook files)
- [ ] DST Only: Increment the `/packages/core` version number if this will be the last PR merged before a release.
- [ ] Complete all sections below.
- [ ] Delete this section once complete

## Description
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/95120

## QA Checklist
- [x] Component maintains 1:1 parity with design mocks
- [x] Text is consistent with what's been provided in the mocks
- [x] Component behaves as expected across breakpoints
- [x] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- [ ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [x] Tab order and focus state work as expected
- [x] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [x] New components are covered by e2e tests; updates to existing components are covered by existing test suite
- [ ] Changes have been tested in vets-website using Verdaccio (if applicable. If not applicable provide reason why)

## Screenshots

**Desktop**
Screenshot 2024-10-18 154528

---

**Mobile**
Screenshot 2024-10-18 154828

## Acceptance criteria
- [ ] QA checklist has been completed
- [ ] Screenshots have been attached that cover desktop and mobile screens

## Definition of done
- [ ] ~~Documentation has been updated, if applicable~~
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by micahchiang — APPROVED** [review]
Hey @1Copenut! Good to see you around here again! Hope you're doing well.

**Comment by jamigibbs** [comment]
@it-harrison is doing some work on [`va-table` sorting](https://github.com/department-of-veterans-affairs/component-library/pull/1358) right now. Do you mind holding off on merging this until he can take a look to make sure there isn't any conflicts?

**Comment by 1Copenut** [comment]
@jamigibbs Sure thing! I'll wait for related work to be done before merging. Should I pull latest `main` and re-run tests before merging when we get to that point?

**Comment by jamigibbs** [comment]
> @jamigibbs Sure thing! I'll wait for related work to be done before merging. Should I pull latest `main` and re-run tests before merging when we get to that point?

@1Copenut Yes! You're good to go to merge in main now and sort out any merge conflicts. I don't think you'll need a re-review if CI is passing but just ping us again if you do. 🙇🏼‍♀️

**Comment by 1Copenut** [comment]
@jamigibbs Merge conflicts are fixed and I did a small logic refactor in my code to avoid duplicating a lot of markup. Did a spot test with NVDA on Chrome and Firefox, and ran axe scans to avoid regressions.

LMK if you see any issue with this change. Otherwise I'll go ahead and merge.

**Review by jamigibbs — APPROVED** [review]

**Pull request merged**
