### PR TITLE
Translate "va-checkbox", "va-checkbox-group", "va-number-input" and "va-radio" component

### PR DESCRIPTION
**Pull request by jhonnyoddball**
## Chromatic

https://add-i18next-to-web-cpmponents--60f9b557105290003b387cd5.chromatic.com

## Description
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1297

This PR adds the following functionality:

### va-checkbox
- Adds translation functionality to component
- Adds Internationalization Story
- Adds Spanish, English and Tagalog languages to Internationalization Story

### va-checkbox-group
- Adds translation functionality to component
- Adds Internationalization Story
- Adds Spanish, English and Tagalog languages to Internationalization Story

### va-radio
- Adds translation functionality to component
- Adds Internationalization Story
- Adds Spanish, English and Tagalog languages to Internationalization Story

### va-number-input
- Adds `Error` param to Internationalization Story
- Adds Tagalog language to Internationalization Story

## Testing done

- Storybook :eyes: 
- E2E updates

### va-checkbox
Screen Shot 2022-11-02 at 12 04 47 PM

### va-checkbox-group
Screen Shot 2022-11-02 at 12 05 20 PM

### va-number-input
Screen Shot 2022-11-02 at 12 05 55 PM

### va-radio
Screen Shot 2022-11-02 at 12 06 24 PM

## Acceptance criteria
- [x] All components have translation functionality

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
Let's update the PR description to be more accurate since this PR doesn't add functionality to the number input component. Also, the title will be going into the release notes as a bullet point, so I think it could be changed to give a reader a good idea of what's changed at a glance

**Comment by jamigibbs** [comment]
@jhonnyoddball Can you make sure that the documentation at the top of the components include the languages like in this example? https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-text-input/va-text-input.tsx#L28-L30

**Review by bkjohnson — APPROVED** [review]
Looks good

**Comment by jhonnyoddball** [comment]
> @jhonnyoddball Can you make sure that the documentation at the top of the components include the languages like in this example? https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-text-input/va-text-input.tsx#L28-L30

Added

**Pull request merged**
