### PR TITLE
Check for node, tagName for va-loading-indicator

### PR DESCRIPTION
**Pull request by Andrew565**
## Chromatic

https://asteele-fix-for-null-loading-nodes-1952--60f9b557105290003b387cd5.chromatic.com

---

## Description
Prevents an error when nodes are either null or don't have a tagName

Closes [#1952](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1952)

## Testing done

Tested in Brave browser's console REPL.

## Screenshots

N/A

## Acceptance criteria
- [X] Appears to correctly filter out non-nodes while still capturing valid nodes.

## Definition of done
- [X] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by acrollet — APPROVED** [review]
This makes sense to me - the worst consequence would be the analytics event not getting fired, which was going to happen anyway in the case this solves for. ty!

**Comment by jamigibbs** [comment]
The branch name is too long for the Chromatic link to work so visual QA needs to be done locally.

**Comment by jamigibbs** [comment]
Tests pass locally 

Screenshot 2023-07-31 at 10 22 17 AM

**Comment by jamigibbs** [comment]
Visually checked locally

Screenshot 2023-07-31 at 10 23 01 AM

**Review by jamigibbs — APPROVED** [review]

**Comment by Andrew565** [comment]
@acrollet This has been merged in, should 'release' on Wednesday, and get merged into vets-website Thursday (give or take a day).

**Pull request merged**
