### PR TITLE
Add icon support to va-accordion-item subheader

### PR DESCRIPTION
**Pull request by mdewey**
## Chromatic

https://1709-accordion-subheader-icon--60f9b557105290003b387cd5.chromatic.com

## Description
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1709

## Testing done
- Storybook
- unit
- screen sizes

### After
image

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] Icon is visible in the sub header
- [ ] formating is maintained for all screen sizes. 

## Notes
 I still need to update the unit tests and documentation. But I am getting a review early

### CODE REVIEW

**Comment by jamigibbs** [comment]
@mdewey This looks good to me so far from the dev side (assuming there might be tests still needed though). I want to loop in @LillyBoot for design feedback as well just to make sure we're ok with how the multiple icons are displaying with the header. I'm not certain about the padding/margins so just want to get her blessing  aswell (and I'm not sure if we also want to add this variation to our Sketch file as well).

https://1709-accordion-subheader-icon--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-accordion--using-icons

Screenshot 2023-04-28 at 12 07 01 PM

**Comment by LillyBoot** [comment]
@mdewey @jamigibbs the header and subheader icons visually compete with each other. I am not sure of the exact solution to this. A couple options could be either increasing the size of the header icon(maybe 20x20) or increasing the margin for the subheader + icon. 

@humancompanion-usds Do you have any thoughts on whether or not to adjust the subheader for this?

**Comment by mdewey** [comment]
@LillyBoot  I am fine with whatever the designers settle with. In our [mocks](https://www.sketch.com/s/32bdb345-fb1f-409b-985f-ff627cb60032) We never had that use case. 

I am going to tag @rtwell  and @coultonbunney-usds  as they are some of the designers on our team for their input.

**Comment by humancompanion-usds** [comment]
I don't have a strong opinion either way. The text is the same size so I'm not surprised that the icons are the same size as well. The thing that looks off to me is the padding between icon and text. It's set to 10px but upon inspection seems to be calculating from the middle of the icon so they're awfully close together. @coultonbunney-usds - Do you have a preference on icon size?

**Comment by mdewey** [comment]
@humancompanion-usds @coultonbunney-usds and @LillyBoot . 

I have updated the to allow for more spacing 
image (1)

**Review by humancompanion-usds — APPROVED** [review]

**Pull request merged**
