### PR TITLE
Update OMBInfo Content

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
Closes <https://github.com/department-of-veterans-affairs/va.gov-team/issues/18881>

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by bkjohnson — COMMENTED** [review]
@KevinMHoffmanUSDS can you give the ok on this? The linked issue states:

> I need the Privacy Act Statement content of the 0994 form to be updated

But this changes a component that is used in many forms/apps on `vets-website`:

- caregivers
- burials
- ask-a-question
- hca
- financial-status
- vre
- pensions
- health-care-questionnaire
- veteran-representative
- edu-benefits
- disability-benefits

**Comment by zurbergram** [comment]
@bkjohnson Text for 18881 was updated to indicate the change is for form system

**Comment by zurbergram** [comment]
@bkjohnson @KevinMHoffmanUSDS https://github.com/department-of-veterans-affairs/va.gov-team/issues/18881 has been updated to reflect reason for this change

**Comment by KevinMHoffmanUSDS** [comment]
@bkjohnson I've taken a look. Danielle Theirry wll need final sign off on this change. I'll loop her in.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bkjohnson @KevinMHoffmanUSDS. Looks like the only change here is the name of the VR&E program. The new name is correct so we're good to go on this PR. Thanks!

**Comment by KevinMHoffmanUSDS** [comment]
@bkjohnson Approved!

**Review by bkjohnson — APPROVED** [review]

**Pull request closed without merging**
