### PR TITLE
Updated css to change the halo focus color

### PR DESCRIPTION
**Pull request by noahgelman**
## Description
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/359

Also related to this PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/684

## Definition of done
- [ ] Form elements have updated focus color

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
I left a comment on the other PR before checking this one :sweat_smile: 

This is assuming that the web components will always be on a light background, correct? I _think_ that might be the case currently, but it won't always be true once more apps/static pages get migrated to use web components. For example, on mobile the footer uses accordions on a dark background:

image

Do we need to solve for someway of determining which color to use right now?

**Comment by pjhill** [comment]
> I left a comment on the other PR before checking this one 😅
> 
> This is assuming that the web components will always be on a light background, correct? I _think_ that might be the case currently, but it won't always be true once more apps/static pages get migrated to use web components. For example, on mobile the footer uses accordions on a dark background:
> > 
> Do we need to solve for someway of determining which color to use right now?

This makes sense. While we are working on this, let's also address the need to have different colors depending on dark/light backgrounds. Is there an existing pattern for determining the light/dark background color of an element?

[Here's ](https://awik.io/determine-color-bright-dark-using-javascript/)an interesting discussion.

**Comment by bkjohnson** [comment]
I can imagine a possible solution for having web components choose their own focus color based on their parent's background.

I'm not aware of an existing pattern for this. Maybe we could use the [CSS style declaration interface](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration) and implement a threshold comparison like in your link:

```js

const val = el.style.getPropertyValue('background-color')

const backgroundType = hsp(val) > someThreshold : 'light' : 'dark'
```

A web component could then use this to set a CSS custom property that would only affect itself and its descendants.

**Comment by noahgelman** [comment]
@rtwell Have you looked into this?

**Comment by noahgelman** [comment]
@bkjohnson Can you look into this for approval? Would like to move to stage

**Comment by caw310** [comment]
@k80bowman , could you look at this since Brooks is out for a few days?

**Comment by k80bowman** [comment]
> @k80bowman , could you look at this since Brooks is out for a few days?

I can take a look at it first thing tomorrow morning

**Comment by k80bowman** [comment]
@noahgelman the change itself looks fine to me, but since this PR was created, this repo has been updated such that the web-components branch is no longer used (I believe). I think this change will have to be made in the `master` branch instead of the web-components branch, but if you want to wait until @bkjohnson gets back to confirm, that's fine. If you make the change on the `master branch` inside the `web-components` directory, the version numbers will need to be updated inside the `web-components` directory and inside the `core` directory.

**Comment by bkjohnson** [comment]
Katy is right - a new PR will have to be made based off of `master`.

**Comment by k80bowman** [comment]
@noahgelman are you going to be able to prioritize transferring this work to a new PR sometime soon?

**Comment by noahgelman** [comment]
@k80bowman Yeah, I'm going to close this and open a new one

**Comment by k80bowman** [comment]
@noahgelman awesome, thank you!

**Comment by bkjohnson** [comment]
Closing this PR. We will work on implementing a double box-shadow design [based on this blog post](https://adhoc.team/2022/02/08/creating-focus-style-for-themable-design-system/). This was [discussed](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/359#issuecomment-1051110667) in a design system council meeting.

**Pull request closed without merging**
