### PR TITLE
va-alert and va-banner: remove v1 code

### PR DESCRIPTION
**Pull request by it-harrison**
## Chromatic

https://3012-remove-v1--alert-and-banner--65a6e2ed2314f7b8f98609d8.chromatic.com

---

## Description
This PR removes v1 code from `va-banner` and `va-alert`.
Closes [3012](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3012)

## QA Checklist
- [ ] Component maintains 1:1 parity with design mocks
- [ ] Text is consistent with what's been provided in the mocks
- [ ] Component behaves as expected across breakpoints
- [ ] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- [ ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [ ] Tab order and focus state work as expected
- [ ] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [ ] New components are covered by e2e tests; updates to existing components are covered by existing test suite
- [ ] Changes have been tested in vets-website using Verdaccio (if applicable. If not applicable provide reason why)

## Acceptance criteria
- [ ] QA checklist has been completed
- [ ] Screenshots have been attached that cover desktop and mobile screens

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by Andrew565 — APPROVED** [review]

**Review by powellkerry — APPROVED** [review]

**Review by jamigibbs — CHANGES_REQUESTED** [review]
Sorry to block this from merging but a couple of things:

- there is a usage of `va-banner` being loaded from Drupal that displays on the home page. Do we want to make sure this is converted first before we remove v1?
- Was there more Storybook stories for `va-banner` from the `type` prop at some point? I was trying to see `warning` but it wasn't there: `'info' | 'warning' | 'error' | 'success' | 'continue'`

Screenshot 2024-08-09 at 1 06 08 PM

**Comment by jamigibbs** [comment]
@it-harrison I'm actually kind of confused now about the `va-banner` markup and the design we want. The [Chromatic link in this PR](https://3012-remove-v1--alert-and-banner--65a6e2ed2314f7b8f98609d8.chromatic.com/?path=/docs/components-va-banner--docs) makes `va-banner` look like `va-alert` (with a left border) but is that right? (It was not flagged by the UI tests strangely) 🤔 

Here is the current [Storybook in production](https://design.va.gov/storybook/?path=/docs/components-va-banner--docs) with the border on the top and a gray background.

**Storybook prod**

Screenshot 2024-08-09 at 3 48 51 PM

**This PR**

Screenshot 2024-08-09 at 3 48 43 PM

I could not find `va-banner` in [Figma](https://www.figma.com/files/team/1278375444205744118/recents-and-sharing/recently-viewed?fuid=1192586511403544015) to confirm.

**Comment by it-harrison** [comment]
@jamigibbs @danbrady in light of trying to find the easiest fix, this is what `va-banner` in this PR looks like when applied to va.gov:

Screenshot 2024-08-14 at 4 20 38 PM

**Comment by danbrady** [comment]
Thanks, @it-harrison. I think that looks okay. Just want to confirm that if it previously used a different alert type, that gets carried through? For example, @jamigibbs screenshot above uses a  "warn" type. So when this gets updated, any `va-banner` with that type will also get that v3 warn type alert?

**Comment by it-harrison** [comment]
@danbrady yes, you can specify the alert type in the banner and it will carry through to the underlying va-alert.

**Review by jamigibbs — APPROVED** [review]
Thanks for the teamwork on this one! 🚀

**Pull request merged**
