### PR TITLE
split text prop in promo banner and add icon to last word in nowrap s…

### PR DESCRIPTION
**Pull request by tmac9494**
split text prop in promo banner and add icon to last word in nowrap span element

## Description
Closes 32078

## Testing done
tested locally, no issues

## Screenshots

Screen Shot 2021-11-05 at 3 10 42 PM

### CODE REVIEW

**Comment by k80bowman** [comment]
Could you please provide a link to the issue here?

**Comment by k80bowman** [comment]
This seems like an OK solution to me, but I'd like @bkjohnson to take a look when he gets in tomorrow.

**Comment by bkjohnson** [comment]
It looks like the [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32078) is already closed. Is this PR still needed?

**Comment by k80bowman** [comment]
@tmac9494 checking in on this, is this PR still needed?

**Comment by pdavies88** [comment]
Closing since PromoBanner React Component has been deprecated

**Pull request closed without merging**
