### PR TITLE
add aria-label to va-pagination navigation landmark

### PR DESCRIPTION
**Pull request by jaredcunha**
## Chromatic

https://1332-aria-label-va-pagination--60f9b557105290003b387cd5.chromatic.com

## Description
Closes [1332](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1332)

## Testing done
- Updated unit tests to include `aria-label="Pagination"`

## Screenshots
Screen Shot 2022-11-10 at 2 55 21 PM

## Acceptance criteria
- [x] Tests continue to pass
- [x] Pagination navigation landmark has name of "Pagination"

## Definition of done
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
cc @SarahKay8

**Review by bkjohnson — COMMENTED** [review]
Sarah, is this new `aria-label` ok or does it need to be worded any differently?

**Comment by caw310** [comment]
@SarahKay8

**Comment by jaredcunha** [comment]
Sort following the naming convention on [va-breadcrumb](https://design.va.gov/storybook/?path=/docs/components-va-breadcrumbs--default) with making the `aria-label` essentially the name of the component. Also wasn't sure if it was worth making something like the `va-breadcrumb`'s `label` prop, which allows developers to specify a name, but otherwise defaults to "Breadcrumb".  With a cursory search on `vets-website`, I didn't see any instances where the `label` prop was used, other than setting it to "Breadcrumb," probably because that's the code example in Storybook.

**Comment by SarahKay8** [comment]
Hey @bkjohnson for some reason, this thread was overlooked in my email. The Aria-label is fine as Pagination

**Review by bkjohnson — APPROVED** [review]

**Pull request merged**
