### PR TITLE
40212 remove react date

### PR DESCRIPTION
**Pull request by k80bowman**
## Chromatic

https://40212-remove-react-date--60f9b557105290003b387cd5.chromatic.com

## Description
Closes department-of-veterans-affairs/va.gov-team#40212
Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1046

Since the React Date component is no longer being used in the `vets-website` repository, we are removing it from the component library.

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
I'd like to pair this with `<MonthYear>` and `<NumberInput>` (since it's only used in `Date` and `MonthYear`) removals if we can.

**Comment by k80bowman** [comment]
I don't think we're ready to remove `<MonthYear>` yet, at least not until we can officially release the web component version and get the [one team using the React component](https://github.com/department-of-veterans-affairs/vets-website/blob/f1b12df865bf0bfdf658f7bdb95dff62bc71b59f/src/applications/financial-status-report/components/EmploymentRecord.jsx#L130) to switch.

I can definitely remove NumberInput, though, good call.

**Comment by bkjohnson** [comment]
I've already got a PR out to remove the remaining `<MonthYear>` usage: https://github.com/department-of-veterans-affairs/vets-website/pull/21329

And I don't think we can remove `NumberInput` without also removing `MonthYear` since [`NumberInput` is used inside `MonthYear`](https://github.com/department-of-veterans-affairs/component-library/blob/e0ac32489464e6443cb19cb4cdbd720bc7e56c87/packages/react-components/src/components/MonthYear/MonthYear.jsx#L7).

**Review by bkjohnson — APPROVED** [review]

**Comment by bkjohnson** [comment]
Before releasing we should merge https://github.com/department-of-veterans-affairs/component-library/pull/527 and a similar PR for `NumberInput` which hasn't been created yet.

**Pull request merged**
