### PR TITLE
Upgrade USWDS@3.7.1

### PR DESCRIPTION
**Pull request by powellkerry**
## Chromatic

https://2512-upgrade-uswds--65a6e2ed2314f7b8f98609d8.chromatic.com

## Description
- Upgrade USWDS package from 3.5.0 to 3.7.1
- Clean up code in va-pagination.scss that is no longer needed due to the upgrade
- Added override in va-memorable-date.scss to disable wrapping

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2512

### Differences documented during regression testing
- va-button: disabled font color is darker
- va-checkbox/va-radio: disabled label font color is darker
- va-memorable-date: .usa-memorable-date added css property `flex-wrap: wrap` which caused the component to always wrap when the month field was a select field. An override was added to prevent this.

## QA Checklist
- [ x] Component maintains 1:1 parity with design mocks
- [ x] Text is consistent with what's been provided in the mocks
- [ x] Component behaves as expected across breakpoints
- [ na - no accessibility changes] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- [ ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [ x] Tab order and focus state work as expected
- [ x] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [ x] New components are covered by e2e tests; updates to existing components are covered by existing test suite
- [ x] Changes have been tested in vets-website using Verdaccio (if applicable. If not applicable provide reason why)

## Screenshots
|| Before | After |
|-|--------|------|
| va-button disabled |Screenshot 2024-02-27 at 2 01 05 PM|Screenshot 2024-02-27 at 2 02 00 PM|
| va-radio disabled |Screenshot 2024-02-27 at 2 03 13 PM|Screenshot 2024-02-27 at 2 04 02 PM|
| va-checkbox disabled |Screenshot 2024-02-27 at 2 05 08 PM|Screenshot 2024-02-27 at 2 05 52 PM|
| va-memorable-date |Screenshot 2024-02-27 at 2 06 37 PM|Screenshot 2024-02-27 at 2 07 15 PM|

## Acceptance criteria
- [ x] QA checklist has been completed
- [ x] Screenshots have been attached that cover desktop and mobile screens

## Definition of done
- [ x] Documentation has been updated, if applicable
- [ x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by danbrady** [comment]
@humancompanion-usds The USWDS updated and added to their disabled colors in 3.6.0 (found in [state colors](https://designsystem.digital.gov/design-tokens/color/state-tokens/#uswds-state-color-tokens)).

Changing the text color from white to base for the disabled button satisfies a11y contrast requirements and still looks disabled. That makes sense to me.

However, I'm a bit concerned that the disabled text color change doesn't look disabled anymore as seen in the screenshots below. Even if we use their other disabled color tokens (they added two more in 3.6.0) the text either does not look disabled or doesn't meet contrast requirements, so we might need to rethink how we style disabled text. 

image

**Review by jamigibbs — APPROVED** [review]
From engineering side this PR looks good. I'm going to tag Ryan though so he can weigh in on the disabled color change that Dan pointed out.

**Comment by rsmithadhoc** [comment]
@danbrady 
I agree that it does not look disabled with the darker color, but as you said that is the lightest it can go while having good contrast. One idea to make it more apparent might be to gray-out the box itself, but that departs from USWDS.
image

**Review by rsmithadhoc — APPROVED** [review]

**Comment by danbrady** [comment]
Nice workaround! I did a little more digging, and it seems like the USWDS does have similar disabled styling for all other form elements *except* checkbox and radio. (They do change the color on the labels, but don't change the form control.) Here's a few of them: 

image

You can see all of them at in this [storybook preview](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cm-disabled-forms-styles/?path=/story/patterns-forms--disabled-form-elements) and more details from the [PR that added](https://github.com/uswds/uswds/pull/5063) them. We should consider updating our disabled styles to match.

**Pull request merged**
