### PR TITLE
Update va-memorable-date error message

### PR DESCRIPTION
**Pull request by rhasselle-oddball**
## Chromatic

https://2121-memorable-date-update-error--60f9b557105290003b387cd5.chromatic.com

## Description
Closes 
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2121

Related
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/531
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/472

## Testing done
Tested the UI in Storybook and `yarn run test` in `web-components`

## Screenshots
image
image

## Acceptance criteria
- [x] Web components without month select continue to use the existing error message
- [x] Web components with month select use new error message

## Definition of done
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by micahchiang — COMMENTED** [review]
This looks fine to me, though I am curious about the translations used for i18n - could you tell me where you got those? I ask because I _think_ there's a process that needs to be used to get official translations, possibly through the state department (I don't know what the actual process is, sorry). This came up recently in a [slack convo](https://dsva.slack.com/archives/G01BJ3ESXL4/p1695839163267169) and the decision was to hold off on translations until they were verified.

**Comment by rhasselle-oddball** [comment]
> This looks fine to me, though I am curious about the translations used for i18n - could you tell me where you got those? I ask because I _think_ there's a process that needs to be used to get official translations, possibly through the state department (I don't know what the actual process is, sorry). This came up recently in a [slack convo](https://dsva.slack.com/archives/G01BJ3ESXL4/p1695839163267169) and the decision was to hold off on translations until they were verified.

Ah ok. I just used Google translate :)  What would be the recommendation for now? just change the en file?  Hm, I can't reach that slack thread. Maybe I'm not on in that channel?

**Comment by micahchiang** [comment]
@rhasselle-oddball - Yeah, I think just for now include the english messaging only :+1:

**Comment by jamigibbs** [comment]
@rhasselle-oddball  Do you mind adding a new line item to the component on [this spreadsheet](https://docs.google.com/spreadsheets/d/1iIg9pP5GG-QFk7DrsyoKJv9GebtYmDuzKf_heqxWks4/edit#gid=0) for us (you should have edit access now)?

**Comment by rhasselle-oddball** [comment]
all issues are resolved

**Review by micahchiang — APPROVED** [review]

**Pull request merged**
