### PR TITLE
build: allow vite to lazy load stencil components

### PR DESCRIPTION
**Pull request by gsong**
## Chromatic

https://feat&#x2F;enable-lazy-load--65a6e2ed2314f7b8f98609d8.chromatic.com

---

## Configuring this pull request

- [ ] Link to any related issues in the description so they can be cross-referenced.
- [ ] Add the appropriate version patch label (`major`, `minor`, `patch`, or `ignore-for-release`).
  - See [How to choose a version number](https://github.com/department-of-veterans-affairs/component-library#how-to-choose-a-version-number) for guidance.
  - Use `ignore-for-release` if files haven't been changed in a component library package. (ie. only Storybook files)
- [ ] DST Only: Increment the `/packages/core` version number if this will be the last PR merged before a release.
- [ ] Complete all sections below.
- [ ] Delete this section once complete

## Description

Enable stencil flag to allow lazy loading in build chains such as vite.

See <https://stenciljs.com/docs/config-extras#enableimportinjection>

## QA Checklist

- [ ] Component maintains 1:1 parity with design mocks
- [ ] Text is consistent with what's been provided in the mocks
- [ ] Component behaves as expected across breakpoints
- [ ] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- [ ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [ ] Tab order and focus state work as expected
- [ ] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [ ] New components are covered by e2e tests; updates to existing components are covered by existing test suite
- [ ] Changes have been tested in vets-website using Verdaccio (if applicable. If not applicable provide reason why)

## Acceptance criteria

- [ ] QA checklist has been completed
- [ ] Screenshots have been attached that cover desktop and mobile screens

## Definition of done

- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by jamigibbs — CHANGES_REQUESTED** [review]
Hi @gsong. Our repository has branch name requirements. Can you review those requirements and resubmit your PR?

https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#branch-naming

**Comment by jamigibbs** [comment]
@gsong  In your new PR, can you also provide us with a comparison of what the build size will be before and after this feature is added?

> Users of this flag should note that they may see an increase in their bundle size.

https://stenciljs.com/docs/config-extras#enableimportinjection

**Comment by gsong** [comment]
Closed in favor of #1415

**Comment by gsong** [comment]
> Hi @gsong. Our repository has branch name requirements. Can you review those requirements and resubmit your PR?
> 
> https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#branch-naming

See #1415.

**Comment by gsong** [comment]
> @gsong In your new PR, can you also provide us with a comparison of what the bundle size will be before and after this feature is added?
> 
> > Users of this flag should note that they may see an increase in their bundle size.
> 
> https://stenciljs.com/docs/config-extras#enableimportinjection

Added in description of #1415.

**Pull request closed without merging**
