### PR TITLE
va-modal: require modalTitle

### PR DESCRIPTION
**Pull request by powellkerry**
## Chromatic

https://2087-require-modal-title--60f9b557105290003b387cd5.chromatic.com

## Description
This change is to make the modal title required. Not having a title was causing the word 'undefined' used as part of ids, and was causing issues with accessibility

- Require modalTitle
- Update storybook to remove example of modal without a title
- 
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2087

## Testing done
Local testing in storybook

## Screenshots
Prop updated to be required:

Screenshot 2023-09-29 at 2 03 34 PM

No other visual changes

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Review by jamigibbs — APPROVED** [review]
Would this cause any issues when we deploy to vets-website? Like do we know if there are many va-modal's out there that don't have a title set?

**Comment by powellkerry** [comment]
Looks like there are 3 instances where a modal does not have a title:
src/applications/claims-status/components/AddFilesForm.jsx
src/applications/static-pages/dependency-verification/components/dependencyVerificationModal.jsx
src/platform/site-wide/announcements/components/HomepageRedesignModal.jsx

I will contact those code owners. From my testing the component does break in storybook when the title isn't set, but it may cause build errors.

**Comment by jamigibbs** [comment]
> Looks like there are 3 instances where a modal does not have a title

Maybe for our own administrative house keeping stuff we should label this a `major` change for our release notes because I guess technically this is an API change for the component.

**Comment by powellkerry** [comment]
With further feedback I am closing this PR and will create another for:
- Add a condition that if modalTitle is not set or is set to an empty string, do not include aria-label="undefined modal" or aria-label=" modal" at all.

**Pull request closed without merging**
