### PR TITLE
Add optional accordion subheading

### PR DESCRIPTION
**Pull request by k80bowman**
## Description
Closes https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/412

## Testing done
Visual.
Added E2E test.

## Screenshots
image

## Acceptance criteria
- [ ] `<p>` element with subheader appears when subheader prop is included
- [ ] `<p>` element does not appear when subheader prop is not included

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by k80bowman** [comment]
@bkjohnson do I need to increase the version number for this as well?

**Review by bkjohnson — APPROVED** [review]
Yeah, I'd say it would be a minor version increase so that we can hopefully make use of this in the liquid templates soon-ish.

We'll also need to add a story to the "actual" storybook :/

**Comment by k80bowman** [comment]
Ok, I added the version bump. I'm going to have to add this to the "actual" storybook in a different PR that merges to master, correct? Do I need to wait until this gets merged to web-components to do that?

**Comment by bkjohnson** [comment]
Yes, unfortunately. What I've been doing is:

1. Merge into `web-components`
1. Make a Github release
1. On master, update the web components dependency to use the new release
1. Modify the story accordingly

Sometimes I'll also test the storybook changes [like this](https://github.com/department-of-veterans-affairs/component-library/pull/65/commits/940908fea1295c4c57b69c9eb9332cb98c0b0573#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R95) before I merge into `web-components` and make the release.

**Pull request merged**
